services:
  web:
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "12345:12345"
    command: nodemon --exec "rails s -b 0.0.0.0"
    environment:
      - RUBY_DEBUG_OPEN=true
      - RUBY_DEBUG_PORT=12345
      - RUBY_DEBUG_HOST=0.0.0.0
    stdin_open: true
    tty: true